### ISSUE TITLE
Need to increase the z index of the canvas

### ISSUE THREAD

**Issue by cdecinkoKnight** [alexandermendes/vue-confetti#42]
Is there a way to increase the value of the canvas z index?  I want to make the confetti cover the entire screen.  With the way our layout was built it is not high enough in the stack and some items are showing over it.

**Comment by isidoravs** [comment]
I had the same issue and styled with CSS (in #30 I answered with the code)

**Comment by alexandermendes** [comment]
☝️ Seems like a reasonable solution. Or, if you don't want to use the default canvas you could always pass another with whatever styling you like via the `canvasId` or `canvasElement` options.

**Comment by Kazbonfim** [comment]
Just for future knowledge: I was having the same problem, using Bootstrap 5 to compose my front-end, it turns out that the AI ​​responses were VERY absurd, so I decided to look in the BS5 docs for modal z-index standards; setting the property zIndex: 1061 (BS5 uses z-index: 1060) beautifully solved the problem, without having to deal with JavaScript anymore.

```
    confetti({
        angle: randomInRange(55, 125),
        spread: randomInRange(50, 70),
        particleCount: randomInRange(50, 100),
        origin: { x: x_center, y: y_center },
        zIndex: 1061, // BS5 default value is z-index: 1060, so 1060 + 1 will solve that problem
    });
```
